routes/admin.php
<?php

use App\Http\Controllers\Admin\featuresController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\newsController;
use App\Http\Controllers\Admin\ProjectsController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\FrontSectionController;
use App\Http\Controllers\Admin\CustomController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\NavBarController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['auth','localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/admin', [HomeController::class, 'index'])->name('admin');

    ###################### Start Routes orders  ######################
    Route::get('/slider-option', [HomeController::class, 'showsliderOption'])->name('slider-option');
    Route::get('/update-slider-option', [HomeController::class, 'updatesliderOption'])->name('update-slider-option');
    Route::post('/save-slider-option', [HomeController::class, 'savesliderOption'])->name('save-slider-option');
    Route::get('/contacts', [HomeController::class, 'contacts'])->name('contacts');
    Route::get('/all-orders', [HomeController::class, 'AllOrders'])->name('AllOrders');
    Route::post('/deleted-orders', [HomeController::class, 'deletedOrders'])->name('deletedOrders');
    Route::post('/deleted-contacts', [HomeController::class, 'deleteddata'])->name('deleteddata');
    ###################### End Routes orders  ######################

    Route::resource('custom-page', CustomController::class);

    ###################### Start Routes resource Services ######################
    Route::resource('Services', ServiceController::class);
    Route::get('deleted-at', [ServiceController::class,'deleted'])->name('services-deleted');
    ###################### End Routes resource Services ######################


    ###################### Start Routes Restore  ######################

    Route::post('restor-Services/{id}', [ServiceController::class,'restor'])->name('restor-service');
    Route::post('restor-features/{id}', [FeaturesController::class,'restor'])->name('restor-features');
    Route::post('restor-projects/{id}', [ProjectsController::class,'restor'])->name('restor-projects');
    Route::post('restor-news/{id}', [newsController::class,'restor'])->name('restor-news');

    ###################### End Routes Restore ######################

    ###################### Start Routes resource slider ######################
    Route::resource('sliders', SliderController::class);
    ###################### End Routes resource slider ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('navbar',NavBarController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('info',InfoController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('front-sections',FrontSectionController::class);
    ###################### End Routes resource NavBar ######################

    ####################### Start Routes resource features ######################
    Route::resource('features', featuresController::class);
    Route::get('deleted-feature', [featuresController::class,'deletedFeature'])->name('feature-deleted');
    ###################### End Routes resource features ######################

    ####################### Start Routes resource projects ######################
    Route::resource('projects', ProjectsController::class);
    Route::get('deleted-project', [ProjectsController::class,'deletedProject'])->name('project-deleted');
    ###################### End Routes resource projects ######################

    ####################### Start Routes resource news ######################
    Route::resource('news', newsController::class);
    Route::get('deleted-news', [newsController::class,'deletedNews'])->name('news-deleted');
    ###################### End Routes resource news ######################

    ####################### Start Routes resource news ######################
    Route::resource('subscription', SubscriptionController::class);
    ###################### End Routes resource news ######################


});

routes/web.php
<?php

use App\Http\Controllers\Website\HomeController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\effects;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () { //...

    ################## Start Route Get Home ###########################
    Route::get('/', [HomeController::class, 'index'])->name('home');
    ################## End Route Get Home ###########################

    ################## Start Route Get profile ###########################
    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');
    ################## End Route Get profile ###########################

    ################## Start Route Get orders ###########################
    Route::post('/orders', [HomeController::class, 'Orders'])->name('orders');
    ################## End Route Get orders ###########################


    ################## Start Route Get about-us ###########################
    Route::get('/about-us', function () {
        return view('website.about-us');
    })->name('aboutus');
    ################## End Route Get about-us ###########################


    ################## Start Route Get contact-us ###########################
    Route::get('/contact-us', function () {
        return view('website.contact-us');
    })->name('contactus');
    ################## End Route Get contact-us ###########################

    ################## Start Route Get site-services ###########################
    Route::get('/site-services', [HomeController::class, 'profile'])->name('siteservice');
    ################## End Route Get site-services ###########################

    ################## Start Route Get site-news ###########################
    Route::get('/site-news', [HomeController::class, 'profile'])->name('sitenews');
    ################## End Route Get site-news ###########################

    ################## Start Route Get site-projects ###########################
    Route::get('/site-projects', [HomeController::class, 'profile'])->name('siteprojects');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get site-projects ###########################
    Route::post('/site-projects', [HomeController::class, 'subscription'])->name('subscription');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get contactus ###########################
    Route::post('/contactus', [HomeController::class, 'contactus'])->name('contactusstore');
    ################## End Route Get contactus ###########################

    Route::get('/site-services',[HomeController::class , 'siteservices' ])->name('siteservices');
    Route::get('/service-details/{id}',[HomeController::class , 'serviceDetails' ])->name('service.details');

    Route::get('/site-news',[HomeController::class , 'sitenews' ])->name('sitenews');
    Route::get('/news-details/{id}',[HomeController::class , 'newsDetails' ])->name('news.details');

    Route::get('/site-projects',[HomeController::class , 'siteprojects' ])->name('siteprojects');
    Route::get('/project-details/{id}',[HomeController::class , 'projectDetails' ])->name('project.details');
    Route::get('/page/{slug}',[HomeController::class , 'customPage' ])->name('customPage');

    Route::post('/site-projects',[HomeController::class , 'subscription' ])->name('subscription');
    Route::post('/contactus',[HomeController::class , 'contactus' ])->name('contactusstore');
});


Route::get("users",[effects::class,"list"]);

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class Service extends Model
{
    use HasFactory;
    use SoftDeletes;
    use HasTranslations;

    protected $fillable = [
        'title',
        'notes',
        'photo',
        'active',
    ];

    public $translatable = ['title', 'notes'];

    public $appends = ['image'];

    public function getImageAttribute()
    {
        return $this->attributes['photo'] != null ? asset('storage/services/' . $this->attributes['photo']) : null;
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Repositories\Eloquent\ServicesRepo;
use App\Http\Requests\Admin\ServiceRequest;
use App\Models\Service;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\File as FacadesFile;

class ServiceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $repo;

    public function __construct(ServicesRepo $repo)
    {

        $this->repo = $repo;
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        $data = $this->repo->getAll();
        $services = Service::all();
        return view('admin.services.index', compact('data', 'services'));
    }

    public function create()
    {
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(ServiceRequest $request)
    {
        try {
            $data = [
                'title' => ['en' => $request->title, 'ar' => $request->title_ar],
                'notes' => ['en' => $request->notes, 'ar' => $request->notes_ar]
            ];
            if ($request->active) {
                $data['active'] = 1;
            } else {
                $data['active'] = 0;
            }
            $file = request()->file('photo');

            if ($file) {
                $data['photo'] = $this->repo->storeFile($file, 'services');
            }

            $this->repo->create($data);
            session()->flash('Add', 'تم اضافه الخدمه بنجاح ');
            return redirect('Services');
        } catch (\Exception $e) {
            return redirect()->back()
                ->with('error', __('app.some_thing_error'));
        }
    }

    /**
     * update the Permission for dashboard.
     *
     * @param Request $request
     * @return Builder|Model|object
     */

    public function deleted()
    {
        $Services = Service::onlyTrashed()->get();
        return view('admin.services.deleted', compact('Services'));
    }

    public function edit($slider)
    {
        try {
            $data = $this->repo->findOrFail($slider);
            return view('admin.services.edit', compact('data'));
        } catch (\Exception $e) {
            return redirect()->back()
                ->with('error', __('app.some_thing_error'));
        }
    }


    /**
     * update a permission.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function update(ServiceRequest $request, $id)
    {

        $item = $this->repo->findOrFail($request->id);
        try {
            $data = [
                'title' => ['en' => $request->title, 'ar' => $request->title_ar],
                'notes' => ['en' => $request->notes, 'ar' => $request->notes_ar]
            ];
            if ($request->active) {
                $data['active'] = 1;
            } else {
                $data['active'] = 0;
            }

            $file = request()->file('photo');

            if ($file) {
                FacadesFile::delete('public/Service/' . $item->photo);
                $data['photo'] = $this->repo->storeFile($file, 'services');
            }

            $this->repo->update($data, $item);

            session()->flash('Edit', 'تم تعديل الخدمه بنجاح ');
            return redirect('Services');
        } catch (\Exception $e) {
            return redirect()->back()
                ->with('error', __('app.some_thing_error'));
        }
    }


    /**
     * Delete more than one permission.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function destroy($service)
    {
        $services = $this->repo->bulkDelete([$service]);
        if (!$services) {
            return __('app.users.cannotdelete');
        }
        return 1;
    }

    public function restor($service)
    {
        $services = $this->repo->bulkRestore([$service]);
        if (!$services) {
            return __('app.users.cannotdelete');
        }
        return 1;
    }
}

resources/views/admin/services/create.blade.php
@extends('layouts.admin.master')
@section('title')
    {{trans('admin/services.Add_new_Service')}}
@endsection
@section('content')
    <div class="page-wrapper">
        <div class="page-content">
            @include('message')
            <div class="card">
                <div class="card-body">
                    <form action="{{route('Services.store')}}" method="post" autocomplete="off"
                          enctype="multipart/form-data">
                        @csrf

                        <div class="row">

                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_name')}}</label>
                                <input type="text" name="title"
                                       class="form-control myInput_en @error('title') is-invalid @enderror" required
                                       value="{{old('title')}}">
                                @error('title')
                                <div class="alert alert-danger">{{$message}}</div>
                                @enderror
                            </div>

                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_name_ar')}}</label>
                                <input type="text" name="title_ar"
                                       class="form-control myInput_ar @error('title_ar') is-invalid @enderror" required
                                       value="{{old('title_ar')}}">
                                @error('title_ar')
                                <div class="alert alert-danger">{{$message}}</div>
                                @enderror
                            </div>

                        </div>

                        <br>


                        <div class="row">
                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_notes')}}</label>
                                <textarea class="form-control myInput_en @error('notes') is-invalid @enderror" rows="5"
                                          name="notes" required> {{old('notes')}} </textarea>
                                @error('notes')
                                <div class="alert alert-danger">{{$message}}</div>
                                @enderror
                            </div>
                        </div>

                        <br>
                        <div class="row">
                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_notes_ar')}}</label>
                                <textarea class="form-control myInput_ar @error('notes_ar') is-invalid @enderror"
                                          rows="5" name="notes_ar" required> {{old('notes_ar')}} </textarea>
                                @error('notes_ar')
                                <div class="alert alert-danger">{{$message}}</div>
                                @enderror
                            </div>
                        </div>

                        <br>

                        <div class="row">
                            <div class="col-xl-9 mx-auto">
                                <p class="text-danger">
                                    * {{trans('admin/services.Attachments_are_of_image_type_only')}}</p>
                                <h6 class="mb-0 text-uppercase">{{trans('admin/services.Attachments')}}</h6>
                                <hr/>
                                <div class="card">
                                    <div class="card-body">
                                        <input id="image-uploadify" name="photo" type="file" accept="image/*" required>
                                    </div>
                                    @error('photo')
                                    <div class="alert alert-danger">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>

                        </div>


                        <br>

                        <div class="row">
                            <div class="col">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" name="active" value="1" type="checkbox"
                                           id="flexSwitchCheckChecked" checked>
                                    <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <button class="btn btn-success">{{trans('admin/services.Add_new_Service')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/services/deleted.blade.php
@extends('layouts.admin.master')
@section('title')
{{trans('admin/services.Archive_Services')}}
@endsection
@section('content')
<div class="page-wrapper">
    <div class="page-content">
        @include('message')
        <div class="card">
            <div class="card-header">
                <p class="h5 text-primary"> {{trans('admin/services.Archive_Services')}}</p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example2" class="table table-striped table-bordered text-center">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>{{trans('admin/services.title')}}</th>
                                <th>{{trans('admin/services.notes')}}</th>
                                <th>{{trans('admin/services.active')}}</th>
                                <th>{{trans('admin/services.photo')}}</th>
                                <th>{{trans('admin/services.Action')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($Services as $row)
                            <tr id="row_{{$row->id}}">
                                <td>{{$loop->iteration}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->notes}}</td>
                                <td>{!! $row->active==1?'<i class="bx bx-check-circle text-success"
                                        aria-hidden="true"></i>':'<i class="bx bx-error text-danger"
                                        aria-hidden="true"></i>'!!}</td>
                                <td>
                                    @if ($row->image)
                                    <a href="{{asset($row->image)}}" data-fancybox="group2">
                                        <img width="75px" height="75px" src="{{asset($row->image)}}"
                                            alt="{{$row->title}}" class="">
                                    </a>
                                    @endif
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary waves-effect waves-light btn-sm"
                                        onclick="reset_alert({{$row->id}},'Services')"><i
                                            class="bx bx-refresh"></i></button>

                                    <button type="button" class="btn btn-danger waves-effect waves-light btn-sm"
                                        onclick="delete_alert({{$row->id}},'Services')"><i
                                            class="bx bx-trash"></i></button>
                                </td>
                                @endforeach
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.admin.master')
@section('title')
    {{trans('admin/services.Edit_Service')}}
@endsection
@section('content')
    <div class="page-wrapper">
        <div class="page-content">
            @include('message')
            <div class="card">
                <div class="card-body">
                    <form action="{{route('Services.update','test')}}" method="post" autocomplete="off" enctype="multipart/form-data">
                       @method('PUT')
                        @csrf

                        <input type="hidden" name="id" value="{{$data->id}}">

                        <div class="row">

                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_name')}}</label>
                                <input type="text" name="title"
                                       class="form-control @error('title') is-invalid @enderror" value="{{ $data->getTranslation('title', 'en') }}}">
                                @error('title')
                                <div class="alert alert-danger">{{$Message}}</div>
                                @enderror
                            </div>


                            <div class="col">
                                <label class="mb-2">{{trans('admin/services.Service_name_ar')}}</label>
                                <input type="text" name="title_ar"
                                       class="form-control @error('title_ar') is-invalid @enderror" value="{{ $data->getTranslation('title', 'ar') }}}">
                                @error('title_ar')
                                <div class="alert alert-danger">{{$Message}}</div>
                                @enderror
                            </div>

                        </div>

                        <br>



                        <div class="row">
                            <div class="col">
                                <label class="mb-2">{{ trans('admin/services.Service_notes') }}</label>
                                <textarea class="form-control" rows="5" name="notes"> {{ $data->getTranslation('notes', 'en') }} </textarea>
                            </div>
                        </div>

                        <br>
                        <div class="row">
                            <div class="col">
                                <label class="mb-2">{{ trans('admin/services.Service_notes_ar') }}</label>
                                <textarea class="form-control" rows="5" name="notes_ar"> {{ $data->getTranslation('notes', 'ar') }} </textarea>
                            </div>
                        </div>

                        <br>

                        <div class="row">
                            <div class="col-xl-9 mx-auto">
                                @if ($data->image)
                                    <a href="{{asset($data->image)}}" data-fancybox="group2">
                                        <img width="75px" height="75px" src="{{asset($data->image)}}" alt="{{$data->title}}" class="">
                                    </a>
                                @endif

                                    <br>
                                    <p class="text-danger">* {{trans('admin/services.Attachments_are_of_image_type_only')}}</p>
                                    <h6 class="mb-0 text-uppercase">{{trans('admin/services.Attachments')}}</h6>
                                <hr/>
                                <div class="card">
                                    <div class="card-body">
                                        <input id="image-uploadify" name="photo" type="file" accept="image/*">
                                    </div>
                                </div>
                            </div>

                        </div>


                        <br>

                        <div class="row">
                            <div class="col">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" name="active" value="1" type="checkbox" id="flexSwitchCheckChecked"
                                           {{$data->active==1?'checked':''}}>
                                    <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <button class="btn btn-success">  {{trans('admin/services.Edit_Service')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.admin.master')
@section('title')
    {{trans('admin/services.Services')}}
@endsection
@section('content')
    <div class="page-wrapper">
        <div class="page-content">
            @include('message')
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <a href="{{route('Services.create')}}" class="btn btn-success">{{trans('admin/services.Add_new_Service')}}</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example2" class="table table-striped table-bordered text-center">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{trans('admin/services.title')}}</th>
                                <th>{{trans('admin/services.notes')}}</th>
                                <th>{{trans('admin/services.active')}}</th>
                                <th>{{trans('admin/services.photo')}}</th>
                                <th>{{trans('admin/services.Action')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($data as $row)
                            <tr id="row_{{$row->id}}">
                                <td>{{$loop->iteration}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->notes}}</td>
                                <td>{!! $row->active==1?'<i class="bx bx-check-circle text-success" aria-hidden="true"></i>':'<i class="bx bx-error text-danger" aria-hidden="true"></i>'!!}</td>
                                <td>
                                    @if ($row->image)
                                        <a href="{{asset($row->image)}}" data-fancybox="group2">
                                            <img width="75px" height="75px" src="{{asset($row->image)}}" alt="{{$row->title}}" class="">
                                        </a>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('Services.edit',$row->id)}}" class="btn btn-success btn-sm"><i class='bx bx-edit'></i></a>
                                    <button type="button" class="btn btn-danger waves-effect waves-light btn-sm" onclick="delete_alert({{$row->id}},'Services')" ><i class="bx bx-trash"></i></button>
                                </td>
                                @endforeach
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection