routes/admin.php
<?php

use App\Http\Controllers\Admin\featuresController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\newsController;
use App\Http\Controllers\Admin\ProjectsController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\FrontSectionController;
use App\Http\Controllers\Admin\CustomController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\NavBarController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['auth','localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/admin', [HomeController::class, 'index'])->name('admin');

    ###################### Start Routes orders  ######################
    Route::get('/slider-option', [HomeController::class, 'showsliderOption'])->name('slider-option');
    Route::get('/update-slider-option', [HomeController::class, 'updatesliderOption'])->name('update-slider-option');
    Route::post('/save-slider-option', [HomeController::class, 'savesliderOption'])->name('save-slider-option');
    Route::get('/contacts', [HomeController::class, 'contacts'])->name('contacts');
    Route::get('/all-orders', [HomeController::class, 'AllOrders'])->name('AllOrders');
    Route::post('/deleted-orders', [HomeController::class, 'deletedOrders'])->name('deletedOrders');
    Route::post('/deleted-contacts', [HomeController::class, 'deleteddata'])->name('deleteddata');
    ###################### End Routes orders  ######################

    Route::resource('custom-page', CustomController::class);

    ###################### Start Routes resource Services ######################
    Route::resource('Services', ServiceController::class);
    Route::get('deleted-at', [ServiceController::class,'deleted'])->name('services-deleted');
    ###################### End Routes resource Services ######################


    ###################### Start Routes Restore  ######################

    Route::post('restor-Services/{id}', [ServiceController::class,'restor'])->name('restor-service');
    Route::post('restor-features/{id}', [FeaturesController::class,'restor'])->name('restor-features');
    Route::post('restor-projects/{id}', [ProjectsController::class,'restor'])->name('restor-projects');
    Route::post('restor-news/{id}', [newsController::class,'restor'])->name('restor-news');

    ###################### End Routes Restore ######################

    ###################### Start Routes resource slider ######################
    Route::resource('sliders', SliderController::class);
    ###################### End Routes resource slider ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('navbar',NavBarController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('info',InfoController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('front-sections',FrontSectionController::class);
    ###################### End Routes resource NavBar ######################

    ####################### Start Routes resource features ######################
    Route::resource('features', featuresController::class);
    Route::get('deleted-feature', [featuresController::class,'deletedFeature'])->name('feature-deleted');
    ###################### End Routes resource features ######################

    ####################### Start Routes resource projects ######################
    Route::resource('projects', ProjectsController::class);
    Route::get('deleted-project', [ProjectsController::class,'deletedProject'])->name('project-deleted');
    ###################### End Routes resource projects ######################

    ####################### Start Routes resource news ######################
    Route::resource('news', newsController::class);
    Route::get('deleted-news', [newsController::class,'deletedNews'])->name('news-deleted');
    ###################### End Routes resource news ######################

    ####################### Start Routes resource news ######################
    Route::resource('subscription', SubscriptionController::class);
    ###################### End Routes resource news ######################


});

routes/web.php
<?php

use App\Http\Controllers\Website\HomeController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\effects;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () { //...

    ################## Start Route Get Home ###########################
    Route::get('/', [HomeController::class, 'index'])->name('home');
    ################## End Route Get Home ###########################

    ################## Start Route Get profile ###########################
    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');
    ################## End Route Get profile ###########################

    ################## Start Route Get orders ###########################
    Route::post('/orders', [HomeController::class, 'Orders'])->name('orders');
    ################## End Route Get orders ###########################


    ################## Start Route Get about-us ###########################
    Route::get('/about-us', function () {
        return view('website.about-us');
    })->name('aboutus');
    ################## End Route Get about-us ###########################


    ################## Start Route Get contact-us ###########################
    Route::get('/contact-us', function () {
        return view('website.contact-us');
    })->name('contactus');
    ################## End Route Get contact-us ###########################

    ################## Start Route Get site-services ###########################
    Route::get('/site-services', [HomeController::class, 'profile'])->name('siteservice');
    ################## End Route Get site-services ###########################

    ################## Start Route Get site-news ###########################
    Route::get('/site-news', [HomeController::class, 'profile'])->name('sitenews');
    ################## End Route Get site-news ###########################

    ################## Start Route Get site-projects ###########################
    Route::get('/site-projects', [HomeController::class, 'profile'])->name('siteprojects');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get site-projects ###########################
    Route::post('/site-projects', [HomeController::class, 'subscription'])->name('subscription');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get contactus ###########################
    Route::post('/contactus', [HomeController::class, 'contactus'])->name('contactusstore');
    ################## End Route Get contactus ###########################

    Route::get('/site-services',[HomeController::class , 'siteservices' ])->name('siteservices');
    Route::get('/service-details/{id}',[HomeController::class , 'serviceDetails' ])->name('service.details');

    Route::get('/site-news',[HomeController::class , 'sitenews' ])->name('sitenews');
    Route::get('/news-details/{id}',[HomeController::class , 'newsDetails' ])->name('news.details');

    Route::get('/site-projects',[HomeController::class , 'siteprojects' ])->name('siteprojects');
    Route::get('/project-details/{id}',[HomeController::class , 'projectDetails' ])->name('project.details');
    Route::get('/page/{slug}',[HomeController::class , 'customPage' ])->name('customPage');

    Route::post('/site-projects',[HomeController::class , 'subscription' ])->name('subscription');
    Route::post('/contactus',[HomeController::class , 'contactus' ])->name('contactusstore');
});


Route::get("users",[effects::class,"list"]);

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded=[];
    public $appends=['image'];


    public function getImageAttribute()
    {
        return $this->attributes['photo'] != null ? asset('storage/sliders/'.$this->attributes['photo'] ) : null;

    }
}

app/Http/Controllers/Admin/SliderController.php
<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Http\Repositories\Eloquent\SliderRepo;
use App\Http\Requests\Admin\SliderRequest ;
use App\Models\Slider;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\File as FacadesFile;

class SliderController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $repo;



    public function __construct(SliderRepo $repo)
    {

       $this->repo = $repo;

    }
    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
       $data=$this->repo->getAll();
        return view('admin.sliders.index', compact('data'));
    }

    public function create()
    {
        return view('admin.sliders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(SliderRequest $request)
    {
      try {
            $data=[
                'title' => $request->title,
                'text' => $request->text
            ];
            if($request->active){
                $data['active']=1;
            }else{
                $data['active']=0;
            }
            $file=request()->file('photo');

            if($file)
            {
                $data['photo'] =  $this->repo->storeFile($file,'sliders');
            }
            $this->repo->create($data);
            session()->flash('Add', 'تم اضافه المنتج بنجاح ');
            return redirect('sliders');

        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()
                ->with('error',__('app.some_thing_error'));
        }
    }

    /**
     * update the Permission for dashboard.
     *
     * @param Request $request
     * @return Builder|Model|object
     */
    public function edit($slider)
    {
        $row=$this->repo->findOrFail($slider);
        return view('admin.sliders.edit',compact('row'));
        // return response()->json($data, 200);
    }

    /**
     * update a permission.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function update(SliderRequest $request,$id)
    {

        $item=$this->repo->findOrFail($request->id);
        try {
            $data=[
                'title' => $request->title,
                'text' => $request->text
            ];
            if($request->active){
                $data['active']=1;
            }else{
                $data['active']=0;
            }

            $file=request()->file('photo');

            if($file)
            {
                FacadesFile::delete('public/slider/images/' . $item->photo);
                $data['photo'] =  $this->repo->storeFile($file,'sliders');
            }

              $this->repo->update($data,$item);

            session()->flash('Edit', 'تم اضافه المنتج بنجاح ');
            return redirect('sliders');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()
                ->with('error',__('app.some_thing_error'));
        }

    }


    /**
     * Delete more than one permission.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function destroy($slider)
    {
        $sliders=$this->repo->bulkDelete([$slider]);
        if (!$sliders ) {
            return __('app.users.cannotdelete');
        }
        return 1;
    }



}

resources/views/admin/sliders/create.blade.php
@extends('layouts.admin.master')
@section('title')
    {{ __('admin/app.create_slider') }}
@endsection
@section('content')
<div class="page-wrapper">
    <div class="page-content">
        @include('message')
        <div class="card">

            <div class="card-body">
                <div class="row">
					<div class="col-xl-7 mx-auto">
						<h6 class="mb-0 text-uppercase">{{ __('admin/app.create_slider') }}</h6>
						<hr/>
						<div class="card border-top border-0 border-4 border-primary">
							<div class="card-body p-5">
								<form class="row g-3" action="{{ route('sliders.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
									<div class="col-md-12">
										<label for="title" class="form-label">{{ __('admin/app.title') }}</label>
										<input type="text" name="title" class="form-control" id="title">
									</div>

									<div class="col-12">
										<label for="text" class="form-label">{{ __('admin/app.text') }}</label>
										<textarea class="form-control" name="text"  id="text" placeholder="{{ __('admin/app.text') }}"></textarea>
									</div>
									<div class="col-12">
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" name="active" value="1" type="checkbox" id="flexSwitchCheckChecked" checked>
                                            <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                        </div>
                                    </div>
									<div class="col-12">
                                        <input type="file" class="form-control" name="photo" aria-label="file example" required accept="image/*" >
									</div>

									<div class="col-12">
										<button type="submit" class="btn btn-primary px-5">{{ __('admin/app.save') }}</button>
									</div>
								</form>

							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/sliders/edit.blade.php
@extends('layouts.admin.master')
@section('title')
    {{ __('admin/app.create_slider') }}
@endsection
@section('content')
<div class="page-wrapper">
    <div class="page-content">
        @include('message')
        <div class="card">

            <div class="card-body">
                <div class="row">
					<div class="col-xl-7 mx-auto">
						<h6 class="mb-0 text-uppercase">{{ __('admin/app.create_slider') }}</h6>
						<hr/>
						<div class="card border-top border-0 border-4 border-primary">
							<div class="card-body p-5">
								<form class="row g-3" action="{{ route('sliders.update',$row->id) }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" name="_method" value="PUT">
                                    <input type="hidden" name="id" id="id" value="{{$row->id}}">
									<div class="col-md-12">
										<label for="title" class="form-label">{{ __('admin/app.title') }}</label>
										<input type="text" name="title" value="{{$row->title}}" class="form-control" id="title">
									</div>

									<div class="col-12">
										<label for="text" class="form-label">{{ __('admin/app.text') }}</label>
										<textarea class="form-control" value="" name="text"  id="text" placeholder="{{ __('admin/app.text') }}">{{ $row->text }}</textarea>
									</div>
									<div class="col-12">
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" name="active" value="1" type="checkbox" id="flexSwitchCheckChecked" {{ $row->active==1?'checked':'' }}>
                                            <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                        </div>
                                    </div>
									<div class="col-lg-4">
                                        @if ($row->image)
                                        <a href="{{asset($row->image)}}" data-fancybox="group2">
                                            <img width="75px" height="50px" src="{{asset($row->image)}}" alt="{{$row->title}}" class="">
                                        </a>
                                        @endif
                                    </div>
									<div class="col-lg-8">
                                        <input type="file" class="form-control" name="photo" aria-label="file example" required accept="image/*" >
									</div>

									<div class="col-12">
										<button type="submit" class="btn btn-primary px-5">{{ __('admin/app.save') }}</button>
									</div>
								</form>

							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/sliders/index.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="page-wrapper">
    <div class="page-content">
        @include('message')

        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-4 pull-right">

                        <a href="{{ route('sliders.create') }}" class="btn btn-success"> {{ __('admin/app.add_new') }} <i class="fa fa-plus" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example2" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ __('admin/app.title') }}</th>
                                <th>{{ __('admin/app.text') }}</th>
                                <th>{{ __('admin/app.active') }}</th>
                                <th>{{ __('admin/app.photo') }}</th>
                                <th>{{ __('admin/app.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $row)
                            <tr id="row_{{$row->id}}">
                                <td>{{$loop->iteration}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->text}}</td>
                                <td>{!! $row->active==1?'<i class="fa fa-check-circle text-success" aria-hidden="true"></i>':'<i class="fa fa-times-circle text-danger" aria-hidden="true"></i>'!!}</td>
                                <td>
                                    @if ($row->image)
                                    <a href="{{asset($row->image)}}" data-fancybox="group2">
                                        <img width="75px" height="50px" src="{{asset($row->image)}}" alt="{{$row->title}}" class="">
                                    </a>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('sliders.edit',$row->id)}}" class="btn btn-primary btn-sm">
                                        <i class="bx bx-edit" aria-hidden="true"></i>
                                    </a>
                                    <button type="button" class="btn btn-danger waves-effect waves-light btn-sm" onclick="delete_alert({{$row->id}},'sliders')" ><i class="bx bx-trash"></i></button>
                                </td>
                            </tr>
                              @endforeach

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection