routes/admin.php
<?php

use App\Http\Controllers\Admin\featuresController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\newsController;
use App\Http\Controllers\Admin\ProjectsController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\FrontSectionController;
use App\Http\Controllers\Admin\CustomController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\NavBarController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['auth','localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/admin', [HomeController::class, 'index'])->name('admin');

    ###################### Start Routes orders  ######################
    Route::get('/slider-option', [HomeController::class, 'showsliderOption'])->name('slider-option');
    Route::get('/update-slider-option', [HomeController::class, 'updatesliderOption'])->name('update-slider-option');
    Route::post('/save-slider-option', [HomeController::class, 'savesliderOption'])->name('save-slider-option');
    Route::get('/contacts', [HomeController::class, 'contacts'])->name('contacts');
    Route::get('/all-orders', [HomeController::class, 'AllOrders'])->name('AllOrders');
    Route::post('/deleted-orders', [HomeController::class, 'deletedOrders'])->name('deletedOrders');
    Route::post('/deleted-contacts', [HomeController::class, 'deleteddata'])->name('deleteddata');
    ###################### End Routes orders  ######################

    Route::resource('custom-page', CustomController::class);

    ###################### Start Routes resource Services ######################
    Route::resource('Services', ServiceController::class);
    Route::get('deleted-at', [ServiceController::class,'deleted'])->name('services-deleted');
    ###################### End Routes resource Services ######################


    ###################### Start Routes Restore  ######################

    Route::post('restor-Services/{id}', [ServiceController::class,'restor'])->name('restor-service');
    Route::post('restor-features/{id}', [FeaturesController::class,'restor'])->name('restor-features');
    Route::post('restor-projects/{id}', [ProjectsController::class,'restor'])->name('restor-projects');
    Route::post('restor-news/{id}', [newsController::class,'restor'])->name('restor-news');

    ###################### End Routes Restore ######################

    ###################### Start Routes resource slider ######################
    Route::resource('sliders', SliderController::class);
    ###################### End Routes resource slider ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('navbar',NavBarController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('info',InfoController::class);
    ###################### End Routes resource NavBar ######################

    ###################### Start Routes resource NAvBar ######################
    Route::resource('front-sections',FrontSectionController::class);
    ###################### End Routes resource NavBar ######################

    ####################### Start Routes resource features ######################
    Route::resource('features', featuresController::class);
    Route::get('deleted-feature', [featuresController::class,'deletedFeature'])->name('feature-deleted');
    ###################### End Routes resource features ######################

    ####################### Start Routes resource projects ######################
    Route::resource('projects', ProjectsController::class);
    Route::get('deleted-project', [ProjectsController::class,'deletedProject'])->name('project-deleted');
    ###################### End Routes resource projects ######################

    ####################### Start Routes resource news ######################
    Route::resource('news', newsController::class);
    Route::get('deleted-news', [newsController::class,'deletedNews'])->name('news-deleted');
    ###################### End Routes resource news ######################

    ####################### Start Routes resource news ######################
    Route::resource('subscription', SubscriptionController::class);
    ###################### End Routes resource news ######################


});

routes/web.php
<?php

use App\Http\Controllers\Website\HomeController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\effects;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () { //...

    ################## Start Route Get Home ###########################
    Route::get('/', [HomeController::class, 'index'])->name('home');
    ################## End Route Get Home ###########################

    ################## Start Route Get profile ###########################
    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');
    ################## End Route Get profile ###########################

    ################## Start Route Get orders ###########################
    Route::post('/orders', [HomeController::class, 'Orders'])->name('orders');
    ################## End Route Get orders ###########################


    ################## Start Route Get about-us ###########################
    Route::get('/about-us', function () {
        return view('website.about-us');
    })->name('aboutus');
    ################## End Route Get about-us ###########################


    ################## Start Route Get contact-us ###########################
    Route::get('/contact-us', function () {
        return view('website.contact-us');
    })->name('contactus');
    ################## End Route Get contact-us ###########################

    ################## Start Route Get site-services ###########################
    Route::get('/site-services', [HomeController::class, 'profile'])->name('siteservice');
    ################## End Route Get site-services ###########################

    ################## Start Route Get site-news ###########################
    Route::get('/site-news', [HomeController::class, 'profile'])->name('sitenews');
    ################## End Route Get site-news ###########################

    ################## Start Route Get site-projects ###########################
    Route::get('/site-projects', [HomeController::class, 'profile'])->name('siteprojects');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get site-projects ###########################
    Route::post('/site-projects', [HomeController::class, 'subscription'])->name('subscription');
    ################## End Route Get site-projects ###########################

    ################## Start Route Get contactus ###########################
    Route::post('/contactus', [HomeController::class, 'contactus'])->name('contactusstore');
    ################## End Route Get contactus ###########################

    Route::get('/site-services',[HomeController::class , 'siteservices' ])->name('siteservices');
    Route::get('/service-details/{id}',[HomeController::class , 'serviceDetails' ])->name('service.details');

    Route::get('/site-news',[HomeController::class , 'sitenews' ])->name('sitenews');
    Route::get('/news-details/{id}',[HomeController::class , 'newsDetails' ])->name('news.details');

    Route::get('/site-projects',[HomeController::class , 'siteprojects' ])->name('siteprojects');
    Route::get('/project-details/{id}',[HomeController::class , 'projectDetails' ])->name('project.details');
    Route::get('/page/{slug}',[HomeController::class , 'customPage' ])->name('customPage');

    Route::post('/site-projects',[HomeController::class , 'subscription' ])->name('subscription');
    Route::post('/contactus',[HomeController::class , 'contactus' ])->name('contactusstore');
});


Route::get("users",[effects::class,"list"]);

resources/views/layouts/admin/footer-script.blade.php
<script src="{{ asset('admin/assets/js/bootstrap.bundle.min.js') }}"></script>
<!--plugins-->
<script src="{{ asset('admin/assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/simplebar/js/simplebar.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/metismenu/js/metisMenu.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/vectormap/jquery-jvectormap-2.0.2.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/vectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/chartjs/js/Chart.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/chartjs/js/Chart.extension.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/sparkline-charts/jquery.sparkline.min.js') }}"></script>
<!--notification js -->
<script src="{{ asset('admin/assets/plugins/notifications/js/lobibox.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/notifications/js/notifications.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/notifications/js/notification-custom-script.js') }}"></script>
{{-- <script src="{{ asset('admin/assets/js/index.js') }}"></script> --}}
<!--app JS-->
<script src="{{ asset('admin/assets/js/app.js') }}"></script>
<script src="{{ asset('js/crud-ajax.js') }}"></script>
<script src="{{ asset('js/sweetalert.min.js') }}"></script>
<script src="{{ asset('js/sweet-alert-script.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/datatable/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/fancy-file-uploader/jquery.ui.widget.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/fancy-file-uploader/jquery.fileupload.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/fancy-file-uploader/jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/fancy-file-uploader/jquery.fancy-fileupload.js') }}"></script>
<script src="{{ asset('admin/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.js') }}"></script>
<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
<script>
    var app_url = "{{ url('/') }}";
    var lang = "{{ app()->getLocale() }}";
    $(document).ready(function() {
        $('#example').DataTable();
    });
</script>
<script>
    $(document).ready(function() {
        var table = $('#example2').DataTable({
            lengthChange: false,
            buttons: ['copy', 'excel', 'pdf', 'print']
        });

        table.buttons().container()
            .appendTo('#example2_wrapper .col-md-6:eq(0)');
    });
</script>

<script>
    $('#fancy-file-upload').FancyFileUpload({
        params: {
            action: 'fileuploader'
        },
        maxfilesize: 1000000
    });
</script>
<script>
    $(document).ready(function() {
        $('#image-uploadify').imageuploadify();
    })
</script>
<script>
    CKEDITOR.editorConfig = function( config ) {
    config.extraPlugins = 'imageuploader';
    };
    CKEDITOR.replace( 'text', );
    </script>

{{-- Cannot write in Arabic --}}
<script>
    $('.myInput_en').keypress(function(e) {
        var regex = /^[A-Za-z-pL\s\-]+$/;
        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
        if (regex.test(str)) {
            return true;
        }
         else {
            e.preventDefault();
            alert('الأحرف العربية غير مسموح بها');
            return false;
        }
    });
</script>

{{-- Cannot write in English --}}
<script>
    $('.myInput_ar').keypress(function(e) {

        var regex = /^[أ-ي-pL\s\-]+$/;
        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
        if (regex.test(str)) {
            return true;
        } else {
            e.preventDefault();
            alert('الأحرف الانجليزية غير مسموح بها');
            return false;
        }
    });
</script>

resources/views/layouts/admin/footer.blade.php
<div class="overlay toggle-icon"></div>
</div>

resources/views/layouts/admin/header.blade.php
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
<link href="{{asset('admin/assets/plugins/fancy-file-uploader/fancy_fileupload.css')}}" rel="stylesheet" />
<link href="{{asset('admin/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.css')}}" rel="stylesheet" />
<link href="{{asset('admin/assets/plugins/datatable/css/dataTables.bootstrap5.min.css')}}" rel="stylesheet" />
<link href="{{ asset('admin/assets/plugins/notifications/css/lobibox.min.css') }}" rel="stylesheet"/>
@if (app()->getLocale()=='ar')

<link href="{{ asset('admin/assets/plugins/notifications/css/lobibox.min.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/assets/plugins/simplebar/css/simplebar.css') }}" rel="stylesheet" />
<link href="{{ asset('admin/assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css') }}" rel="stylesheet" />
<link href="{{ asset('admin/assets/plugins/metismenu/css/metisMenu.min.css') }}" rel="stylesheet" />
<!-- loader-->
<link href="{{ asset('admin/assets/plugins/datatable/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" />
<link href="{{ asset('admin/assets/css/pace.min.css') }}" rel="stylesheet" />
<script src="{{ asset('admin/assets/js/pace.min.js')}}"></script>
<!-- Bootstrap CSS -->
<link href="{{ asset('admin/assets/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin/assets/css/app.css') }}" rel="stylesheet">
<link href="{{ asset('admin/assets/css/icons.css') }}" rel="stylesheet">
<!-- Theme Style CSS -->
<link rel="stylesheet" href="{{ asset('admin/assets/css/dark-theme.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assets/css/semi-dark.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assets/css/header-colors.css') }}" />

@else
<link href="{{ asset('admin/assetsEn/plugins/notifications/css/lobibox.min.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/assetsEn/plugins/vectormap/jquery-jvectormap-2.0.2.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/assetsEn/plugins/simplebar/css/simplebar.css') }}" rel="stylesheet" />
<link href="{{ asset('admin/assetsEn/plugins/perfect-scrollbar/css/perfect-scrollbar.css') }}" rel="stylesheet" />
<link href="{{ asset('admin/assetsEn/plugins/metismenu/css/metisMenu.min.css') }}" rel="stylesheet" />
<!-- loader-->
<link href="{{ asset('admin/assetsEn/css/pace.min.css') }}" rel="stylesheet" />
<script src="{{ asset('admin/assetsEn/js/pace.min.js')}}"></script>
<!-- Bootstrap CSS -->
<link href="{{ asset('admin/assetsEn/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
<link href="{{ asset('admin/assetsEn/css/app.css') }}" rel="stylesheet">

<link href="{{ asset('admin/assetsEn/css/icons.css') }}" rel="stylesheet">
<!-- Theme Style CSS -->
<link rel="stylesheet" href="{{ asset('admin/assetsEn/css/dark-theme.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assetsEn/css/semi-dark.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assetsEn/css/header-colors.css') }}" />

@endif

resources/views/layouts/admin/master.blade.php
<!DOCTYPE html>
<html dir="{{ app()->getLocale() == 'ar' ? 'rtl' : 'ltr' }}" lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8" />
    <meta name="description" content="this my acount to my son" />
    <meta name="keywords" content="Html,css,utf,javascript" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @yield('meta')
    <title>@yield('title')</title>
    @include('layouts.admin.header')
</head>

<body style="font-family: 'Cairo', sans-serif;">
<div class="wrapper">
    <!--sidebar wrapper -->
    @include('layouts.admin.sidebar')
    <!--end sidebar wrapper -->
    <!--start header -->
    @include('layouts.admin.navbar')
    <!--end header -->
    <!--start page wrapper -->
        @yield('content')
        @include('layouts.admin.footer')

</div>





    @include('layouts.admin.footer-script')
</body>

</html>

resources/views/layouts/admin/navbar.blade.php
<header>
    <div class="topbar d-flex align-items-center">
        <nav class="navbar navbar-expand">

            <div class="mobile-toggle-menu"><i class='bx bx-menu'></i>
            </div>

            <div class="top-menu ms-auto">
                <ul class="navbar-nav align-items-center">


                    <li class="nav-item dropdown dropdown-large">

                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret position-relative" href="#"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @if (App()->getLocale() == 'ar')
                                <i class="flag-icon flag-icon-eg"></i>
                            @else

                                <i class="flag-icon flag-icon-us"></i>
                            @endif
                        </a>


                        <div class="dropdown-menu dropdown-menu-end">
                            @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)<a
                                    rel="alternate" hreflang="{{ $localeCode }}"
                                    href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                                    <div class="msg-header"> {{ $properties['native'] }}
                                        <p class="msg-header-title ms-auto">
                                        <p class="msg-header-clear ms-auto">
                                            @if ($localeCode == 'ar')
                                                <i class="flag-icon flag-icon-eg"></i>
                                            @else
                                                <i class="flag-icon flag-icon-us"></i>
                                            @endif
                                        </p>
                                        </p>

                                    </div>
                                </a>
                            @endforeach

                            <div class="header-notifications-list">

                            </div>

                        </div>
                    </li>


                    <li class="nav-item dropdown dropdown-large">

                        <div class="dropdown-menu dropdown-menu-end">

                            <div class="header-message-list">
                                {{--  --}}
                            </div>

                        </div>
                    </li>


                </ul>
            </div>


            <div class="user-box dropdown">
                <a class="d-flex align-items-center nav-link dropdown-toggle dropdown-toggle-nocaret" href="#"
                    role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ asset('admin/assets/images/avatars/avatar-2.png') }}" class="user-img"
                        alt="user avatar">
                    <div class="user-info ps-3">
                        <p class="user-name mb-0">{{ auth()->user()->name }}</p>
                        <p class="designattion mb-0"></p>
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li class="dropdown-item"> <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                            <i class='bx bx-log-out-circle'></i> {{ __('Log Out') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</header>

resources/views/layouts/admin/sidebar.blade.php
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div>
            <img src="{{ asset('storage/front/' . websiteInfo_hlp('logo')) }}" class="logo-icon" alt="logo icon">
        </div>
        <div>
            <h4 class="logo-text">{{ websiteInfo_hlp('website_name') }}</h4>
        </div>
        <div class="toggle-icon ms-auto"><i class='bx bx-arrow-to-left'></i>
        </div>
    </div>
    <ul class="metismenu" id="menu">
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-home-circle'></i>
                </div>
                <div class="menu-title"> {{ __('admin/app.homepage') }}</div>
            </a>
            <ul>
                <li><a href="{{route('admin')}}"><i class="bx bx-right-arrow-alt"></i> {{ __('admin/app.homepage') }}</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-cog'></i>
                </div>
                <div class="menu-title">{{ __('admin/app.main_setting') }}</div>
            </a>
            <ul>
                <li><a href="{{ route('Services.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.services') }}</a></li>

                <li><a href="{{ route('features.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.features') }}</a></li>

                <li><a href="{{ route('AllOrders') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.orders') }}</a></li>

                <li><a href="{{ route('projects.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.projects') }}</a></li>

                <li><a href="{{ route('news.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.news') }}</a></li>

                <li><a href="{{ route('sliders.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.sliders') }}</a></li>

                <li><a href="{{ route('navbar.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.navbar') }}</a></li>
                <li><a href="{{ route('subscription.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.sbscriptions') }}</a></li>
                <li><a href="{{ route('contacts') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.contacts') }}</a></li>
            </ul>
        </li>

        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-info-circle'></i>
                </div>
                <div class="menu-title">{{ __('admin/app.website_info') }}</div>
            </a>
            <ul>

                <li><a href="{{ route('info.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.website_info') }}</a></li>
                <li><a href="{{ route('slider-option') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.slider-option') }}</a></li>
                <li><a href="{{ route('front-sections.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.control_front') }} </a></li>
                <li><a href="{{ route('custom-page.index') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.custom_page') }} </a></li>

            </ul>
        </li>


        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-info-square'></i>
                </div>
                <div class="menu-title">{{ __('admin/app.archive') }}</div>
            </a>
            <ul>

                <li><a href="{{ route('services-deleted') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.services') }}</a></li>

                <li><a href="{{ route('feature-deleted') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.features') }}</a></li>

                <li><a href="{{ route('project-deleted') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.projects') }}</a></li>

                <li><a href="{{ route('news-deleted') }}"><i class="bx bx-right-arrow-alt"></i>{{ __('admin/app.news') }}</a></li>

            </ul>
        </li>




    </ul>

</div>